# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_SSR <- function(D, Delta) {
    .Call('_DAS_compute_SSR', PACKAGE = 'DAS', D, Delta)
}

compute_stress <- function(D, Dhat) {
    .Call('_DAS_compute_stress', PACKAGE = 'DAS', D, Dhat)
}

main_bmds <- function(D, X0, sigg0, a, alpha, maxiter, constant, verbose, betas) {
    .Call('_DAS_main_bmds', PACKAGE = 'DAS', D, X0, sigg0, a, alpha, maxiter, constant, verbose, betas)
}

emds_gamma0 <- function(dmat) {
    .Call('_DAS_emds_gamma0', PACKAGE = 'DAS', dmat)
}

my_invgamma <- function(alpha, beta) {
    .Call('_DAS_my_invgamma', PACKAGE = 'DAS', alpha, beta)
}

