# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_SSR <- function(D, Delta) {
    .Call('_DAS_compute_SSR', PACKAGE = 'DAS', D, Delta)
}

compute_stress <- function(D, Dhat) {
    .Call('_DAS_compute_stress', PACKAGE = 'DAS', D, Dhat)
}

main_bmds <- function(D, X0, sigg0, a, alpha, maxiter, constant, verbose, betas) {
    .Call('_DAS_main_bmds', PACKAGE = 'DAS', D, X0, sigg0, a, alpha, maxiter, constant, verbose, betas)
}

my_invgamma <- function(alpha, beta) {
    .Call('_DAS_my_invgamma', PACKAGE = 'DAS', alpha, beta)
}

rcpparma_hello_world <- function() {
    .Call('_DAS_rcpparma_hello_world', PACKAGE = 'DAS')
}

rcpparma_outerproduct <- function(x) {
    .Call('_DAS_rcpparma_outerproduct', PACKAGE = 'DAS', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_DAS_rcpparma_innerproduct', PACKAGE = 'DAS', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_DAS_rcpparma_bothproducts', PACKAGE = 'DAS', x)
}

